### ISSUE TITLE
'int' object has no attribute 'backward'

### ISSUE THREAD

**Issue by wangpeng138375** [ghchen18/cdalign#1]
When training EAM-Output model with the params of vanilla Transformer frozen, I got "`'int' object has no attribute 'backward'`".

**Comment by wangpeng138375** [comment]
Which parameters are used when 'fairseq-preprocess' the origin data?

**Comment by piyusharma08** [comment]
Hi @wangpeng138375 ,
Did you find solution for it? I got the same error.

**Comment by jucho2725** [comment]
@piyusharma08 It might be too late, but I want to share my solution with other ppl.

The author's code assumes that the dataset is preprocessed with the argument `--dataset-impl lazy` 
The error appears when your dataset is not stored with same format(e.g. 'raw').

The solution could be:
1. preprocess your dataset with the same impl format
2. or you can edit the code from "fairseq/tasks/translation.py" to read `align_dataset` with a different data format 
(here is an example)

```
        if indexed_dataset.dataset_exists(align_path, impl='lazy'):
            align_dataset = data_utils.load_indexed_dataset(align_path, None, 'lazy')
        elif indexed_dataset.dataset_exists(reverse_align_path, impl='lazy'):
            align_dataset = data_utils.load_indexed_dataset(reverse_align_path, None, 'lazy')
```
