### ISSUE TITLE
IndexError in generate_align.py

### ISSUE THREAD

**Issue by BeatsLeo** [ghchen18/cdalign#10]
This error occured when using bash extract_alignment.sh to extract alignment in task2.
It seems like sample_id is lager than the fix length of align_sents and get the error IndexError: list index out of range.
In line 90-95:
![image](https://github.com/ghchen18/cdalign/assets/72809862/fbacb241-edcb-43dc-a93f-2246909de77e)

How can I solve this problem?

**Comment by ghchen18** [comment]
You can increase the fix length as you like.

**Comment by BeatsLeo** [comment]
thx!
