### ISSUE TITLE
The usage of extract_phrase.py

### ISSUE THREAD

**Issue by BeatsLeo** [ghchen18/cdalign#11]
Sorry to bother, I'am stuck in using extract_phrase.py to extract the constraints.

How can I using this scripts to extract the constrains from my own dataset, it seems like there always has some files lack. What other files should I need to provide except the source and target bpe text according to the arguments in extract_phrase.py.

It has stumped me for a long time, very appreciate if you can give me some detail of how to use it.

**Comment by ghchen18** [comment]
You can refer to the example [here](https://github.com/ghchen18/cdalign/blob/main/scripts/run_test.sh#L41).

**Comment by BeatsLeo** [comment]
Thanks a lot. I've read over the run_test.sh and try to run it. But it seems like I am missing vocab.$tgt. How can I get the raw_reference with the vocab? Do I need to manually generate it or generate it by some scripts.

**Comment by yugaljain1999** [comment]
@BeatsLeo I am also facing same issue, were you able to solve it yet?

**Comment by ghchen18** [comment]
> Thanks a lot. I've read over the run_test.sh and try to run it. But it seems like I am missing vocab.$tgt. How can I get the raw_reference with the vocab? Do I need to manually generate it or generate it by some scripts.

you can use the `fastbpe getvocab` command in the [fastBPE repo](https://github.com/glample/fastBPE).
