### ISSUE TITLE
External fairseq model loading issue

### ISSUE THREAD

**Issue by ayushbits** [ghchen18/cdalign#4]
Hi @ghchen18 ,

Thanks for the code. Your work is very interesting.
I am trying to load a translation model trained on fairseq v0.10.0 which, as expected, is giving errors since your paper is trained on fairseq v0.9.
Is there any way to load the v0.10 model (since this version is in existence since Nov 2020) ?

Thanks,

**Comment by ghchen18** [comment]
Hi, Ayushbits,

what are the giving errors? Are they caused by the mismatched names? If debug step by step, the model may be loaded.

**Comment by piyusharma08** [comment]
Hi, thank you for your reply @ghchen18 . I'm also working with @ayushbits on same thread.
This is the error I got: 

**RuntimeError:** Error(s) in loading state_dict for TransformerModel:
	**Missing key(s) in state_dict: "decoder.embed_out".** 
	**Unexpected key(s) in state_dict: "decoder.output_projection.weight".** 
	size mismatch for encoder.embed_tokens.weight: copying a param with shape torch.Size([32104, 1536]) from checkpoint, the shape in current model is torch.Size([32105, 512]).
	size mismatch for encoder.layers.0.self_attn.k_proj.weight: copying a param with shape torch.Size([1536, 1536]) from checkpoint, the shape in current model is torch.Size([512, 512]).
	size mismatch for encoder.layers.0.self_attn.k_proj.bias: copying a param with shape torch.Size([1536]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for encoder.layers.0.self_attn.v_proj.weight: copying a param with shape torch.Size([1536, 1536]) from checkpoint, the shape in current model is torch.Size([512, 512]).
	size mismatch for encoder.layers.0.self_attn.v_proj.bias: copying a param with shape torch.Size([1536]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for encoder.layers.0.self_attn.q_proj.weight: copying a param with shape torch.Size([1536, 1536]) from checkpoint, the shape in current model is torch.Size([512, 512]).
	size mismatch for encoder.layers.0.self_attn.q_proj.bias: copying a param with shape torch.Size([1536]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for encoder.layers.0.self_attn.out_proj.weight: copying a param with shape torch.Size([1536, 1536]) from checkpoint, the shape in current model is torch.Size([512, 512]).
	size mismatch for encoder.layers.0.self_attn.out_proj.bias: copying a param with shape torch.Size([1536]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for encoder.layers.0.self_attn_layer_norm.weight: copying a param with shape torch.Size([1536]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for encoder.layers.0.self_attn_layer_norm.bias: copying a param with shape torch.Size([1536]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for encoder.layers.0.fc1.weight: copying a param with shape torch.Size([4096, 1536]) from checkpoint, the shape in current model is torch.Size([2048, 512]).
... 
...

I have also trained a model from scratch using your code and compared the state['model'] keys with state['model'] keys of fairseq v0.10.0 model ( the translation model which I'm trying to load), Although **decoder.output_projection.weight** is present in v0.10.0 model which i can get rid of, I couldn't find the key "**decoder.embed_out**" in both of them.
I have used the custom transformer architecture for v0.10.0 model using --user-dir tag.

Can you help me with the possible reason for the same and the corresponding solution?

Thanks.

**Comment by ghchen18** [comment]
Hi, Piyush,

I think the error is not caused by the fairseq version difference.  It is caused by the difference of model structure and dictionary  between pretrained model and the v0.9.0 code. 

You can check the difference of the task dictionary (for example the first and last several tokens).  and set the values of args `encoder_ffn_embed_dim`,  `encoder_embed_dim`, `decoder_ffn_embed_dim`,  `decoder_embed_dim`, to make them consistant between your pretrained model and the v0.9.0 code.  you may also need to set `share_all_embeddings` as True. 

Hope these helps,

Best,

**Comment by piyusharma08** [comment]
Hi @ghchen18,

I tried loading another [model](https://github.com/pytorch/fairseq/tree/main/examples/translation) (transformer.wmt18.en-de) which has the same `encoder_ffn_embed_dim` , `encoder_embed_dim` etc. still I'm getting same error as above i.e. **Missing key(s) in state_dict: "decoder.embed_out".**  I could not find this key in the model trained using your code.

**Errors**

**RuntimeError: Error(s) in loading state_dict for TransformerModel:
	Missing key(s) in state_dict: "decoder.embed_out".** 
	size mismatch for encoder.embed_tokens.weight: copying a param with shape torch.Size([32070, 512]) from checkpoint, the shape in current model is torch.Size([32071, 512]).
	size mismatch for decoder.embed_tokens.weight: copying a param with shape torch.Size([32070, 512]) from checkpoint, the shape in current model is torch.Size([32071, 512]).

I'm not sure why I'm getting this one extra row (32071 --> 32071), maybe because of this missing key. Can you look into this?

Thanks

**Comment by ghchen18** [comment]
Hi,

The `embed_out` is used in `fairseq/models/transformer.py#L559`, you can check the config of  `share_input_output_embed` (expected to be true). 

You can print the first/last several tokens in your dictionary to check the extra dictionary token (e.g. dictionary.symbols[:20]).

Hope these help.
Best

**Comment by piyusharma08** [comment]
Hi,
I am able to get rid of the error `Missing key(s) in state_dict: "decoder.embed_out"` by setting the arg `share_all_embedding=False` and `share_input_output_embed=True`.
The only error that remains is:
**size mismatch for encoder.embed_tokens.weight: copying a param with shape torch.Size([32104, 1536]) from checkpoint, the shape in current model is torch.Size([32104, 512]).**

I'm passing args **--use-dir** with model architecture and dimensions (the model architecture has embed_dim as 1536).  As per my knowledge, the model should see dimension from dir provided in --user-dir and accordingly set the tensor, but somehow it is not happening. If these dimensions are needed to be changed in the code, can you please point me to that file?

Thank you.

**Comment by ghchen18** [comment]
Hi,

you can try to set the dimension in the scritps, by `--encoder-embed-dim 1536  --decoder-embed-dim 1536 `.  If not work, you might have to debug step by step.

Best,

**Comment by piyusharma08** [comment]
Hi @ghchen18 ,

I changed the default arguments in transformer.py and now I can successfully load the model.
Thank You for your help.

**Comment by ghchen18** [comment]
That's good.
