### ISSUE TITLE
Where does ‘bak’ come from in ”--srcdict $fseq/bak/dict.${src}.txt“ in extract_alignment.sh?

### ISSUE THREAD

**Issue by Ruby-G0** [ghchen18/cdalign#6]
The scripts are sa follows:
echo "Start processing alignment data into fairseq data format"
python preprocess.py -s $src -t $tgt --dataset-impl lazy \
    --workers 8 --destdir $fseq --align-suffix align --joined-dictionary  \
    --trainpref $fseq/bpe/train --validpref $fseq/bpe/valid \
    --srcdict $fseq/bak/dict.${src}.txt --process-only-alignment

**Comment by Ruby-G0** [comment]
Does `--srcdict $fseq/bak/dict.${src}.txt` means to use the vanilla data dictionary?

**Comment by ghchen18** [comment]
yes.

**Comment by Ruby-G0** [comment]
thx!
