### ISSUE TITLE
Is the loop over word_num correct in `extract_phrase.py`?

### ISSUE THREAD

**Issue by manestay** [ghchen18/cdalign#8]
Hi, I am using your repository to train some experiments. I appreciate the documentation.

I had a question about this line in the scripts to extract constraints:
https://github.com/ghchen18/cdalign/blob/74389f7271a78933c51a4abf3f0e38480738b4fa/scripts/extract_phrase.py#L184

I wanted to confirm the behavior. So this means it will run with values `word_num = {0,1,2}`. But does it make sense for `max_src_len=0` in the call to `phrase_extraction()`? That is, there's no way to extract a phrase of length 0. I checked the value of `cons_dicts[0]` right before writing to file, and found that it is `None`.

So is this an unintended behavior, and the loop should actually be `for word_num in range(1,3+1)`? Or am I misunderstanding?

**Comment by manestay** [comment]
Another potential bug. Currently, rerunning the exact same `extract_phrase.py` command will give you different constraints each time. The issue is at:
https://github.com/ghchen18/cdalign/blob/74389f7271a78933c51a4abf3f0e38480738b4fa/scripts/extract_phrase.py#L106

This should be `sorted(bp)` to make it a list. Otherwise, `bp` is a set, which has is unordered, and thus does not obey the random seed. But after the change, the same command gives the consistent same constraints.

**Comment by ghchen18** [comment]
Thank you for your comment. The word_num is incorrect and it will miss the word_num=3 case. I have revised it in the updated version.

**Comment by manestay** [comment]
Great! Thanks again for the clear documentation and scripts.

You will also need to modify this line
https://github.com/ghchen18/cdalign/blob/de8c173ce2e3dbc14d0a093054cbadb41fc19c36/scripts/extract_phrase.py#L183
To `[[], [], [], []]`
